sudo: required
install:
- pip install -r requirements.txt
- pip install codecov
- rm wiring.fzz
language: python
python:
- '2.7'
script:
- coverage run preTestSubFunctions.py
after_success:
- codecov
- eval "$(ssh-agent -s)"
- ssh -o "StrictHostKeyChecking no" g_fabian_lukas_blank@git.resin.io
- git remote add resin g_fabian_lukas_blank@git.resin.io:g_fabian_lukas_blank/control.git
- git checkout master
- git merge dev
- git push -u origin master
- git push resin master
