before_install:
  - openssl aes-256-cbc -K $encrypted_ddb69df631e0_key -iv $encrypted_ddb69df631e0_iv -in id.enc -out id -d
install: pip install --user -r requirements.txt
language: python
python:
    - "3.6"
  script:
    - testSubFunctions.py
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/id # this key should have push access
  - ssh-add .travis/id
  - git remote add resin g_fabian_lukas_blank@git.resin.io:g_fabian_lukas_blank/control.git 
  - git push resin master