sudo: required
install:
- pip install -r requirements.txt
- pip install codecov
language: python
python:
- '2.7'
script:
- coverage run testSubFunctions.py
after_success:
- ls
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id
- ssh-add .travis/id
- ssh -o "StrictHostKeyChecking no" g_fabian_lukas_blank@git.resin.io
- git remote add resin g_fabian_lukas_blank@git.resin.io:g_fabian_lukas_blank/control.git
- git checkout master
- git merge dev
- git push -u origin master 
- git push resin master
