install:
- pip install --user -r requirements.txt
language: python
python:
- '3.6'
script:
- testSubFunctions.py
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id
- ssh-add .travis/id
- git remote add resin g_fabian_lukas_blank@git.resin.io:g_fabian_lukas_blank/control.git
- git push resin master
